Towny-Enabled: false
Allow-Duplicates: true
Town-Duplicate-Prefix: ''
Town-Duplicate-Suffix: '_v%num%'
Town-Rarity: Common
Town-Series: 'Towny'
Town-Type: 'Town'
Nation-Duplicate-Prefix: ''
Nation-Duplicate-Suffix: '_v%num%'
Nation-Rarity: Uncommon
Nation-Series: 'Towny'
Nation-Type: 'Nation'
Has-Shiny: true
